"""scaffold all models for berlinopoly app

Revision ID: 78d37728afc3
Revises: ea7a869267b6
Create Date: 2025-02-08 20:36:31.930888

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '78d37728afc3'
down_revision = 'ea7a869267b6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event_cards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('Positive', 'Negative', 'Neutral', name='event_type'), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('balance_change', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fields',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('type', sa.Enum('property', 'event', 'start', 'prison', name='field_type'), nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('rent_base', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('rent_with_house', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('games',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('game_name', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Enum('ongoing', 'complete', name='game_status'), nullable=False),
    sa.Column('winner_user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['winner_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('game_event_decks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('event_card_id', sa.Integer(), nullable=False),
    sa.Column('position_in_queue', sa.Integer(), nullable=False),
    sa.Column('is_drawn', sa.Boolean(), nullable=True),
    sa.Column('drawn_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['event_card_id'], ['event_cards.id'], ),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('game_properties',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('property_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('free', 'purchased', 'house_built', name='property_status'), nullable=False),
    sa.Column('current_rent', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ),
    sa.ForeignKeyConstraint(['property_id'], ['fields.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users_games',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('current_balance', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('current_position', sa.String(length=255), nullable=False),
    sa.Column('next_player', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users_games')
    op.drop_table('game_properties')
    op.drop_table('game_event_decks')
    op.drop_table('games')
    op.drop_table('fields')
    op.drop_table('event_cards')
    # ### end Alembic commands ###
